# Generated by Django 5.1.7 on 2025-03-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Paid', 'Paid')], default='Active', max_length=20),
        ),
    ]
