# Generated by Django 5.1.7 on 2025-03-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loan_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='category',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Business', 'Business')], default='Personal', max_length=20),
        ),
    ]
